site_name: Dynamic Typing
site_url: https://mannyvv.github.io/code-jam-site-test/
repo_url: https://github.com/Mannyvv/cj25-monumental-monsteras-team-repo
repo_name: cj25-monumental-monsteras-team

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False

nav:
    - Home: index.md
    - WASD Input: keyboard_input.md
    - Platformer: platformer_input.md
    - color_mixer_input: color_mixer_input.md
    - DJ Keyboard: audio_style_input.md

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
  - search
    

theme:
  icon:
    repo: fontawesome/brands/github
  name: 
    material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: dynamic_typing_colors
  font:
    text: Lexend Deca
  features:
    - navigation.instant  
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    - navigation.sections

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
       custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
