site_name: Dynamic Typing
site_url: https://mannyvv.github.io/code-jam-site-test/
repo_url: https://github.com/Mannyvv/cj25-monumental-monsteras-team-repo
repo_name: cj25-monumental-monsteras-team


nav:
    - Home: index.md
    - RPG_Text: platformer_input.md
    - keyboard_input: keyboard_input.md
    - color_mixer_input: color_mixer_input.md
    - audio_style_input: audio_style_input.md

theme:
  name: 
    material
  custom_dir: overrides  
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: dynamic_typing_colors
  font:
    text: Lexend Deca
  features:
    - navigation.instant  
    ##Choose tabs up top or on the left side
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

    
    
  plugins:
    - social
    - typeset


extra_css:
  - stylesheets/extra.css